/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://mrutwrrtzyjfrqddqcve.supabase.co"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ydXR3cnJ0enlqZnJxZGRxY3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3MTI2MTgsImV4cCI6MjA4NDI4ODYxOH0.tSGc5L3J92T9UCazKipFTLrG-b8L27vdA3jGt-z8EoA"